### PR TITLE
Sharpmake and server compilation for Mac

### PR DESCRIPTION
**Pull request by dri-richard**
Adds Sharpmake app for Mac, sufficient to build the server app.

- Add Sharpmake application
- Shared.sharpmake_mac.cs for Mac build, that builds Xcode project / workspace files (builds server/sample/all workspaces, but samples can't be built due to dependency on dx11)
- Disable xcopy step when building on Mac
- GLFW libs for Mac
- Shell script equivalent to .bat file

### CODE REVIEW

**Comment by sammyfreg** [comment]
That's nice. Ideally, I would prefer it in the same file to avoid having to maintain 2 files, but for now this is ok. 

I don't have a MacOS to test, so I will assume it works just like you needed.

Good job.

**Review by sammyfreg — APPROVED** [review]

**Comment by starlight-traveler** [comment]
@dri-richard Did you encounter any issues regarding parsing errors with the generated Sharpmake files? Not familiar with the tool chain explicitly, but I can't understand why everything is throwing a parsing error.

**Comment by dri-richard** [comment]
@starlight-traveler it looks like the output is truncated above (I don't see any errors) - can you post it again?

**Comment by starlight-traveler** [comment]
No errors get generated with Sharpmake:

> [00:00] sharpmake 0.18.1
> [00:00]   arguments: /sources(@"Build/shared.sharpmake_mac.cs", @"Build/nocompatibility.sharpmake.cs", @"Build/netImgui.sharpmake.cs") /verbose()
> [00:00]   directory: /Users/foo/Documents/Projects/C++/GUI/netImgui
> [00:00]   platform: mac - Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
> [00:00]   compiled with framework: .NETCoreApp,Version=v5.0
> [00:00]   running on framework: .NET 5.0.17
> [00:00] 
> [00:02] input sources: 
> [00:02]   /Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs
> [00:02]   /Users/foo/Documents/Projects/C++/GUI/netImgui/Build/nocompatibility.sharpmake.cs
> [00:02]   /Users/foo/Documents/Projects/C++/GUI/netImgui/Build/netImgui.sharpmake.cs
> [00:04]   building projects and solutions configurations using 10 tasks...
> [00:04]     build done in 0.4 sec
> [00:04]   linking projects dependencies...
> [00:04]     link done in 0.0 sec
> [00:04]   generating projects and solutions...
> [00:04]     generation done in 0.3 sec
> [00:04]   38 projects generated:
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/DearImguiIndex16Lib.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/DearImguiIndex16Lib.xcodeproj/xcshareddata/xcschemes/DearImguiIndex16Lib.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/DearImguiIndex32Lib.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/DearImguiIndex32Lib.xcodeproj/xcshareddata/xcschemes/DearImguiIndex32Lib.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/DearImguiServerLib.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/DearImguiServerLib.xcodeproj/xcshareddata/xcschemes/DearImguiServerLib.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImgui16Lib.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImgui16Lib.xcodeproj/xcshareddata/xcschemes/NetImgui16Lib.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImgui32Lib.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImgui32Lib.xcodeproj/xcshareddata/xcschemes/NetImgui32Lib.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImguiLib (Disabled).xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImguiLib (Disabled).xcodeproj/xcshareddata/xcschemes/NetImguiLib (Disabled).xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImguiServer.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImguiServer.xcodeproj/xcshareddata/xcschemes/NetImguiServer.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleBackground.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleBackground.xcodeproj/xcshareddata/xcschemes/SampleBackground.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleBasic.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleBasic.xcodeproj/xcshareddata/xcschemes/SampleBasic.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleCompression.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleCompression.xcodeproj/xcshareddata/xcschemes/SampleCompression.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleDisabled.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleDisabled.xcodeproj/xcshareddata/xcschemes/SampleDisabled.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleDualUI.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleDualUI.xcodeproj/xcshareddata/xcschemes/SampleDualUI.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleFontDPI.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleFontDPI.xcodeproj/xcshareddata/xcschemes/SampleFontDPI.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleIndex16Bits.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleIndex16Bits.xcodeproj/xcshareddata/xcschemes/SampleIndex16Bits.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleIndex32Bits.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleIndex32Bits.xcodeproj/xcshareddata/xcschemes/SampleIndex32Bits.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleNewFrame.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleNewFrame.xcodeproj/xcshareddata/xcschemes/SampleNewFrame.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleNoBackend.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleNoBackend.xcodeproj/xcshareddata/xcschemes/SampleNoBackend.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleSingleInclude.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleSingleInclude.xcodeproj/xcshareddata/xcschemes/SampleSingleInclude.xcscheme
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleTextures.xcodeproj/project.pbxproj
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleTextures.xcodeproj/xcshareddata/xcschemes/SampleTextures.xcscheme
> [00:04]   3 solutions generated:
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios_netImgui_All.xcworkspace/contents.xcworkspacedata
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios_netImgui_Sample.xcworkspace/contents.xcworkspacedata
> [00:04]     /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios_netImgui_Server.xcworkspace/contents.xcworkspacedata
> [00:04]   Results:
> [00:04]     projects  (   38 configurations)    38 generated,     0 up-to-date
> [00:04]     solutions (    6 configurations)     3 generated,     0 up-to-date
> [00:04]   time: 4.82 sec.
> [00:04]   completed on 07/04/2024 10:05:33.
> [00:04] 0 errors, 0 warnings

The error I am seeing when I open the workspaces in Xcode, here is just trying to list the schemes, same errors occur when I try to open anything in GUI:

> Command line invocation:
>     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace xcode4ios_netImgui_All.xcworkspace -list
> 
> User defaults from command line:
>     IDEPackageSupportUseBuiltinSCM = YES
> 
> 2024-07-04 10:08:52.280 xcodebuild[19436:696589] Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0., NSJSONSerializationErrorIndex=0}
> 2024-07-04 10:08:52.280 xcodebuild[19436:696589] [MT] IDEFileReferenceDebug: [Load] <IDEFileReference, 0x600001607900: name:SampleDisabled path:absolute:/Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleDisabled.xcodeproj> Failed to load container at path: /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleDisabled.xcodeproj, Error: Error Domain=Xcode3ProjectErrorDomain Code=2 "The project ‘SampleDisabled’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
> 
> Path: /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleDisabled.xcodeproj" UserInfo={NSLocalizedDescription=The project ‘SampleDisabled’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
> 
> Path: /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleDisabled.xcodeproj}
> --- xcodebuild: WARNING: Unable to open project file '/Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleDisabled.xcodeproj' in workspace 'xcode4ios_netImgui_All.xcworkspace'.
> 2024-07-04 10:08:52.282 xcodebuild[19436:696589] Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0., NSJSONSerializationErrorIndex=0}
> 2024-07-04 10:08:52.282 xcodebuild[19436:696589] [MT] IDEFileReferenceDebug: [Load] <IDEFileReference, 0x60000161c200: name:DearImguiServerLib path:absolute:/Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/DearImguiServerLib.xcodeproj> Failed to load container at path: /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/DearImguiServerLib.xcodeproj, Error: Error Domain=Xcode3ProjectErrorDomain Code=2 "The project ‘DearImguiServerLib’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
> 
> Path: /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/DearImguiServerLib.xcodeproj" UserInfo={NSLocalizedDescription=The project ‘DearImguiServerLib’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
> 
> Path: /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/DearImguiServerLib.xcodeproj}
> --- xcodebuild: WARNING: Unable to open project file '/Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/DearImguiServerLib.xcodeproj' in workspace 'xcode4ios_netImgui_All.xcworkspace'.
> 2024-07-04 10:08:52.284 xcodebuild[19436:696589] Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0., NSJSONSerializationErrorIndex=0}
> 2024-07-04 10:08:52.284 xcodebuild[19436:696589] [MT] IDEFileReferenceDebug: [Load] <IDEFileReference, 0x600001606400: name:NetImguiServer path:absolute:/Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImguiServer.xcodeproj> Failed to load container at path: /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImguiServer.xcodeproj, Error: Error Domain=Xcode3ProjectErrorDomain Code=2 "The project ‘NetImguiServer’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
> 
> Path: /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImguiServer.xcodeproj" UserInfo={NSLocalizedDescription=The project ‘NetImguiServer’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
> 
> Path: /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImguiServer.xcodeproj}
> --- xcodebuild: WARNING: Unable to open project file '/Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/NetImguiServer.xcodeproj' in workspace 'xcode4ios_netImgui_All.xcworkspace'.
> 2024-07-04 10:08:52.285 xcodebuild[19436:696589] Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0., NSJSONSerializationErrorIndex=0}
> 2024-07-04 10:08:52.285 xcodebuild[19436:696589] [MT] IDEFileReferenceDebug: [Load] <IDEFileReference, 0x600001608b00: name:SampleTextures path:absolute:/Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleTextures.xcodeproj> Failed to load container at path: /Users/foo/Documents/Projects/C++/GUI/netImgui/_projects/xcode4ios/SampleTextures.xcodeproj, Error: Error Domain=Xcode3ProjectErrorDomain Code=2 "The project ‘SampleTextures’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
> 

Let me know if I am just missing something obvious. Usually the parse failure is due to Git version control being weird and adding "=====", and "<<<<" to the file if the merge isn't done correctly, but looking in the project workspaces, I see none of that.

**Comment by sammyfreg** [comment]
I wonder if a more up to date Sharpmake library could help?
If all else fails, the projects are fairly simple to recreate from scratch without Sharpmake.

**Comment by starlight-traveler** [comment]
I eventually got there with the Cmake pull request which works fairly easily on Mac/Unix distributions, but was curious about this method documentation.

Replaced the Sharpmake library with a new version, seems like the .cs files are out of date, will try and update it, seems like its just bringing up obsolete calls.

`[00:00] sharpmake 0.51.0 (0.51.0+0.51.0.Commits.0.Branch.HEAD.Sha.b5533c7a2cb055fbaadcba9a5ddde4002718afe3)
[00:00]   arguments: /sources(@'Build/shared.sharpmake_mac.cs', @'Build/nocompatibility.sharpmake.cs', @'Build/netImgui.sharpmake.cs') /verbose()
[00:00]   directory: /Users/foo/Documents/Projects/C++/GUI/netImgui
[00:00]   platform: mac - Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
[00:00]   compiled with framework: .NET 6.0
[00:00]   running on framework: .NET 8.0.6
[00:00]
[00:00] input sources:
[00:00]   /Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs
[00:00]   /Users/foo/Documents/Projects/C++/GUI/netImgui/Build/nocompatibility.sharpmake.cs
[00:00]   /Users/foo/Documents/Projects/C++/GUI/netImgui/Build/netImgui.sharpmake.cs
[00:01] [ERROR]/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(35,13): error CS0619: 'DevEnv.xcode4ios' is obsolete: 'xcode4ios has been deprecated, please use 'xcode''
[00:01] [ERROR]/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(146,63): error CS0117: 'Project.Configuration.OutputType' does not contain a definition for 'IosApp'
[00:01] [ERROR]/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(158,25): error CS0619: 'Options.XCode.Compiler.SystemFrameworks' is obsolete: 'Deprecated. Use `conf.XcodeSystemFrameworks` instead.'
[00:01] [ERROR]/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(159,25): error CS0619: 'Options.XCode.Compiler.SystemFrameworks' is obsolete: 'Deprecated. Use `conf.XcodeSystemFrameworks` instead.'
[00:01] [ERROR]/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(160,25): error CS0619: 'Options.XCode.Compiler.SystemFrameworks' is obsolete: 'Deprecated. Use `conf.XcodeSystemFrameworks` instead.'
[00:01] [ERROR]/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(161,25): error CS0619: 'Options.XCode.Compiler.SystemFrameworks' is obsolete: 'Deprecated. Use `conf.XcodeSystemFrameworks` instead.'
[00:01] [WARNING]/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(163,21): warning CS0618: 'Options.XCode.Compiler.Exceptions' is obsolete: 'Deprecated. Use `CppExceptions`, `ObjCExceptions`, or `ObjCARCExceptions` instead.'
[00:01] [ERROR]/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/netImgui.sharpmake.cs(93,25): error CS0619: 'DevEnv.xcode4ios' is obsolete: 'xcode4ios has been deprecated, please use 'xcode''
[00:01] [ERROR]/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(47,44): error CS0619: 'DevEnv.xcode4ios' is obsolete: 'xcode4ios has been deprecated, please use 'xcode''
[00:01] [ERROR]/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/netImgui.sharpmake.cs(112,31): error CS0619: 'DevEnv.xcode4ios' is obsolete: 'xcode4ios has been deprecated, please use 'xcode''
[00:01] [ERROR]
Error:
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(35,13): error CS0619: 'DevEnv.xcode4ios' is obsolete: 'xcode4ios has been deprecated, please use 'xcode''
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(146,63): error CS0117: 'Project.Configuration.OutputType' does not contain a definition for 'IosApp'
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(158,25): error CS0619: 'Options.XCode.Compiler.SystemFrameworks' is obsolete: 'Deprecated. Use `conf.XcodeSystemFrameworks` instead.'
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(159,25): error CS0619: 'Options.XCode.Compiler.SystemFrameworks' is obsolete: 'Deprecated. Use `conf.XcodeSystemFrameworks` instead.'
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(160,25): error CS0619: 'Options.XCode.Compiler.SystemFrameworks' is obsolete: 'Deprecated. Use `conf.XcodeSystemFrameworks` instead.'
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(161,25): error CS0619: 'Options.XCode.Compiler.SystemFrameworks' is obsolete: 'Deprecated. Use `conf.XcodeSystemFrameworks` instead.'
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(163,21): warning CS0618: 'Options.XCode.Compiler.Exceptions' is obsolete: 'Deprecated. Use `CppExceptions`, `ObjCExceptions`, or `ObjCARCExceptions` instead.'
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/netImgui.sharpmake.cs(93,25): error CS0619: 'DevEnv.xcode4ios' is obsolete: 'xcode4ios has been deprecated, please use 'xcode''
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(47,44): error CS0619: 'DevEnv.xcode4ios' is obsolete: 'xcode4ios has been deprecated, please use 'xcode''
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/netImgui.sharpmake.cs(112,31): error CS0619: 'DevEnv.xcode4ios' is obsolete: 'xcode4ios has been deprecated, please use 'xcode''

[00:01] 	While running /Users/foo/Documents/Projects/C++/GUI/netImgui/Build/Sharpmake/Sharpmake.Application
	@07/04/2024 10:38:00: Exception message:
	/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(35,13): error CS0619: 'DevEnv.xcode4ios' is obsolete: 'xcode4ios has been deprecated, please use 'xcode''
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(146,63): error CS0117: 'Project.Configuration.OutputType' does not contain a definition for 'IosApp'
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(158,25): error CS0619: 'Options.XCode.Compiler.SystemFrameworks' is obsolete: 'Deprecated. Use `conf.XcodeSystemFrameworks` instead.'
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(159,25): error CS0619: 'Options.XCode.Compiler.SystemFrameworks' is obsolete: 'Deprecated. Use `conf.XcodeSystemFrameworks` instead.'
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(160,25): error CS0619: 'Options.XCode.Compiler.SystemFrameworks' is obsolete: 'Deprecated. Use `conf.XcodeSystemFrameworks` instead.'
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(161,25): error CS0619: 'Options.XCode.Compiler.SystemFrameworks' is obsolete: 'Deprecated. Use `conf.XcodeSystemFrameworks` instead.'
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(163,21): warning CS0618: 'Options.XCode.Compiler.Exceptions' is obsolete: 'Deprecated. Use `CppExceptions`, `ObjCExceptions`, or `ObjCARCExceptions` instead.'
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/netImgui.sharpmake.cs(93,25): error CS0619: 'DevEnv.xcode4ios' is obsolete: 'xcode4ios has been deprecated, please use 'xcode''
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/shared.sharpmake_mac.cs(47,44): error CS0619: 'DevEnv.xcode4ios' is obsolete: 'xcode4ios has been deprecated, please use 'xcode''
/Users/foo/Documents/Projects/C++/GUI/netImgui/Build/netImgui.sharpmake.cs(112,31): error CS0619: 'DevEnv.xcode4ios' is obsolete: 'xcode4ios has been deprecated, please use 'xcode''


	Stack trace:
	Root stack trace:
   at Sharpmake.Assembler.LogCompilationResult(EmitResult result, Boolean throwErrorException) in /_/Sharpmake/Assembler.cs:line 584
   at Sharpmake.Assembler.Compile(IBuilderContext builderContext, IEnumerable`1 syntaxTrees, String libraryFile, HashSet`1 fileReferences) in /_/Sharpmake/Assembler.cs:line 545
   at Sharpmake.Assembler.Compile(IBuilderContext builderContext, String[] files, String libraryFile, HashSet`1 references) in /_/Sharpmake/Assembler.cs:line 493
   at Sharpmake.Assembler.Build(IBuilderContext builderContext, String libraryFile, String[] sources) in /_/Sharpmake/Assembler.cs:line 450
   at Sharpmake.Assembler.BuildAssembly(IBuilderContext context, String[] sourceFiles) in /_/Sharpmake/Assembler.cs:line 115
   at Sharpmake.Builder.BuildAndLoadAssembly(IList`1 sharpmakeFiles, IBuilderContext context, IEnumerable`1 parsers, IEnumerable`1 flowParsers) in /_/Sharpmake/Builder.cs:line 531
   at Sharpmake.Builder.BuildAndLoadAssembly(IList`1 sharpmakeFiles, BuilderCompileErrorBehavior compileErrorBehavior) in /_/Sharpmake/Builder.cs:line 506
   at Sharpmake.Builder.LoadSharpmakeFiles(BuilderCompileErrorBehavior compileErrorBehavior, String[] sharpmakeFiles) in /_/Sharpmake/Builder.cs:line 561
   at Sharpmake.Builder.LoadSharpmakeFiles(String[] sharpmakeFiles) in /_/Sharpmake/Builder.cs:line 556
   at Sharpmake.Application.Program.CreateBuilder(BaseBuildContext context, Argument parameters, Boolean allowCleanBlobs, Boolean generateDebugSolution) in /_/Sharpmake.Application/Program.cs:line 665
   at Sharpmake.Application.Program.CreateBuilderAndGenerate(BaseBuildContext buildContext, Argument parameters, Boolean generateDebugSolution) in /_/Sharpmake.Application/Program.cs:line 460
   at Sharpmake.Application.Program.Main() in /_/Sharpmake.Application/Program.cs:line 307`

**Comment by dri-richard** [comment]
It seems to work fine for me (but read to the end):
```
(base) dri@dris-mbp-2 _projects % /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace xcode4ios_netImgui_All.xcworkspace -list
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace xcode4ios_netImgui_All.xcworkspace -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

objc[38628]: Class XROS1_0SimRuntime is implemented in both /Library/Developer/CoreSimulator/Volumes/xrOS_21N5233f/Library/Developer/CoreSimulator/Profiles/Runtimes/xrOS 1.0.simruntime/Contents/MacOS/xrOS 1.0 (0x10c6840e0) and /Library/Developer/CoreSimulator/Volumes/xrOS_21N5207f/Library/Developer/CoreSimulator/Profiles/Runtimes/xrOS 1.0.simruntime/Contents/MacOS/xrOS 1.0 (0x11227c0e0). One of the two will be used. Which one is undefined.
objc[38628]: Class XROS1_0SimRuntime is implemented in both /Library/Developer/CoreSimulator/Volumes/xrOS_21N5233f/Library/Developer/CoreSimulator/Profiles/Runtimes/xrOS 1.0.simruntime/Contents/MacOS/xrOS 1.0 (0x10c6840e0) and /Library/Developer/CoreSimulator/Volumes/xrOS_21N5165g/Library/Developer/CoreSimulator/Profiles/Runtimes/xrOS 1.0.simruntime/Contents/MacOS/xrOS 1.0 (0x1125c00e0). One of the two will be used. Which one is undefined.
Information about workspace "xcode4ios_netImgui_All":
    Schemes:
        DearImguiIndex16Lib
        DearImguiIndex32Lib
        DearImguiServerLib
        NetImgui16Lib
        NetImgui32Lib
        NetImguiLib (Disabled)
        NetImguiServer
        SampleBackground
        SampleBasic
        SampleCompression
        SampleDisabled
        SampleDualUI
        SampleFontDPI
        SampleIndex16Bits
        SampleIndex32Bits
        SampleNewFrame
        SampleNoBackend
        SampleSingleInclude
        SampleTextures
```

But if I rename my folder so that it has '++' in the path like yours, I get exactly the same errors. So, I think it's just a problem with your pathname. I've tried both a few times - without the characters, it's good, with it is not.
```
Path: /Users/dri/Documents/GitHub/netimgui++/_projects/xcode4ios/SampleBasic.xcodeproj}
--- xcodebuild: WARNING: Unable to open project file '/Users/dri/Documents/GitHub/netimgui++/_projects/xcode4ios/SampleBasic.xcodeproj' in workspace 'xcode4ios_netImgui_All.xcworkspace'.
2024-07-04 15:43:32.616 xcodebuild[38864:4307407] Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0., NSJSONSerializationErrorIndex=0}
2024-07-04 15:43:32.616 xcodebuild[38864:4307407] [MT] IDEFileReferenceDebug: [Load] <IDEFileReference, 0x600002116a00: name:NetImgui16Lib path:absolute:/Users/dri/Documents/GitHub/netimgui++/_projects/xcode4ios/NetImgui16Lib.xcodeproj> Failed to load container at path: /Users/dri/Documents/GitHub/netimgui++/_projects/xcode4ios/NetImgui16Lib.xcodeproj, Error: Error Domain=Xcode3ProjectErrorDomain Code=2 "The project ‘NetImgui16Lib’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
```

**Comment by starlight-traveler** [comment]
Lol, there it is, so obvious. Can't believe I fell for an age old Unix issue. Sorry for the bother, and thank you so much for the help!

**Pull request merged**
