### PR TITLE
Add sokol backend for NetImguiServerApp

### PR DESCRIPTION
**Pull request by THISISAGOODNAME**
Add [sokol](https://github.com/floooh/sokol) backend for NetImguiServerApp

### CODE REVIEW

**Review by sammyfreg — CHANGES_REQUESTED** [review]
HAL_SheelCommand has been removed from the API, it should also be deleted here

**Review by sammyfreg — CHANGES_REQUESTED** [review]
Expand the filename to include full sokol name 'xxx_HAL_SokolApp' 'xxx_HAL_SokolGfx'

**Comment by sammyfreg** [comment]
Can you change the pull to the dev branch?

**Comment by sammyfreg** [comment]
I didn't know about Sokol. I guess you did this integration to support Metal on MacOS?

**Comment by THISISAGOODNAME** [comment]
> Can you change the pull to the dev branch?

I'll do it.

> I didn't know about Sokol. I guess you did this integration to support Metal on MacOS?

I do this mainly for html/webassembly platform, though it can support macos or android/ios.

**Pull request closed without merging**
